language: python
services:
- docker
before_install:
- cd app
jobs:
  include:
  - stage: test
    script: python manage.py test
  - stage: build
    script:
    - docker build -t bladewing/bahnplan-next .
    - bash ../docker_push
stages:
- test
- build
env:
  global:
    secure: eQC0D6mEeAOqZgm+bk5mSFQsil1bzl1nDq+H7XbDyptcAgDn7l93r0Szmchymb/ZY8YWoQBpJTi0M9L/DOLnXEvPsuxvgnapFCKFa7gfFbV0lbcQXQVaMaINW6Hij4iRBM9NFrSUPBGx+iuUwtKZVk5KOkVBD/spwlcthrb7J1dThHOGA84zq4BtSW+LMdeGz0XEezhZ0jOf/DmmgM/e3nQRqs4WPfs4f8JIQe8IL5SFG4eBfOTRqk4OB9bBxFkTU0rK7IONGpnQM5QcpRXwCffRpzKoVDR6huj1TisfQOhtFMcbaaU8WoDzq0+myOoWPVgb+I7D96FFwM71YuIRuCjePSIm4wUifTnslV8FsgqePEcMhjdrbRatRIgn7KuBttaoHRK7uOF9xZB4DhugSqXe6XB09k+HbHNM1Jcsi+GRZt96lKHrusBiH2Pf7WF50bu7tgTXgMJlYg3312fFvhUyvEi1/wPLJS//98gjMd876xGeXCxd3UjsdDoK6ME8Rxsh65GD06V9oENyVv0tK9YUmPM3nvZ2YGstMgjP+2cJ/a4Acdt6XXrfCVIhW/TtKXafeMl6FA9pvtyQwUKiq5a9R8qCJH6mQhu3TqmPzuDntYRYQEoaNJgdIx1WAk8v+luZVPAiiK5EXsluQfvTIW/ngwPquWBVvg4DI0HXIjQ=
