language: python
services:
- docker
before_install:
- cd app
jobs:
  include:
  - stage: test
    script: python manage.py test
  - stage: build
    script:
    - docker build -t bladewing/bahnplan-next .
    - bash ../docker_push
stages:
- test
- build
env:
  global:
    secure: LW+xz8F+fRFb+k5p6WVwqsATSwaN2ti5m1UIDkQXC6QEB4MIkOOCdpIksKsV3Cs21Xjj0xZrj5qH5skpEpIW+TN3MYbxNJU6LIoTj8/NMqsEaMQPuFUVy38DGK6tFGvPM3Lsw3zXXIQCb3TUlk2PxgLpmWuaNWjXsIwDCDVmQTo9eT4WqHsLhm6feqJu4vp+dvqS6Za0jLR+8XpLR8r4mhHhn6aO/n93/3gtcIS7tUMPI8t0t+xwBQoC+evQ0hD9H65wj/sJpeyqJgsyuYY8OUNHhdtCPsaBxFA0XpIsE35/kANBvemOqtZ48KKIwR3RpRzXE8y4qLZQ1XndmuKSZIltBiuU4v6OfOT77Dv84Lyx4GsswlmEJlfU8LUkn2kmNR9/SyGFe/oxNwKw0WqaYm0HZFMRe3ttysrv0+u1zN6NopNVzodbNR1KRsmcBhR5BzJLN+va8BXHwNlAwq7mWP1esg/YEax2P3Sb6cWgOnqCeKfQu+49Qe0n8Aaj6rhrinct93rrPDOHisfRgHUe6RdzSeGAyq1Qjyz+Hg1caD/X5D/CzbBtclIJDdQW4X52QIghQ0GmQPsxxoNctKB56ZiIYvViqzGbSvFtW9ov0m9ilyvVEf/Dd3DjFPMEuZu+CXTNA6uoPQS3HAOJ9y3VbPKmQEm1vCCAdWAwIo57rsk=
dd:
  secure: tCMNpybyvov2AdQw4i61EFZGWp/rExiggp84ACO1eULV9ybVWFo1vukwcAWIoIhH8VNFqL+PHVjZm+3Op84lK+6N4vYuj5BR/s2bb0NWWWPM0iHzDBhmjr/Mf903qK99JDUXsQdN6NznIhrf9d9YNYp9V+f1uLjtUkFtj3HOgSfWnF3c51GGCRLxkh253sS9FIZhLri199uyKJcpLVzIgTLoPCsOhHI5+w37WSXhxdjqxpHr8GXykHpLR3OWncEz6VRNwNxbD4LzEe42aKo+6GmJHvH6No3XtPEeWhTPV6PeJ79kz3ZTd4MnDHMTRmAfooMTU9++BNBY8hyJAnkb3Pbq9z0/KtiM1lnDy6t0xWBTEfWvQ0dkYQJ8siRQR082DeV+jFgOLETK+ZscRm1KbhZp6i4Xzhk192XXwOUG8TCsMxJevNfvjvNaIQQsFCpkyrsHoKzsTokE3+L5yURAirUHmRWyaskViND5gGYzQd17Xdq2/ON4qYmAGpX8wYKz4t72Wln4ZUQhWlTou1duxk+PV0eSgULRiPH9xMIasc1ZhUCpEPH/RN5Dygs58uOcfu/puq1WfziHogxVjfbd4wNVe6bTyr9Oh7x7tRh0ryGKktAdBkX/QnIrgx6gWudh8lW2dJH05XkhQoTnjNAP9UVk2Hne1F9IVUZqaXAVo5Y=
