# Generated by Django 3.1.2 on 2020-11-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_auto_20201102_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringentry',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='singleentry',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
