name: test_Django
on: [ pull_request, push ] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: py-actions/py-dependency-install@v4
      - run: pip install flake8
      - run: pip install -r requirements.txt # install all our dependencies for the project
      - run: python manage.py makemigrations # run makemigrations
      - run: python manage.py migrate # run migrate
      - run: python manage.py test # run tests