name: test_Django
on: [ push ] # activates the workflow when there is a push
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - uses: py-actions/py-dependency-install@v4
        with:
          path: "app/requirements.txt"
      - run: python manage.py makemigrations # run makemigrations
      - run: python manage.py migrate # run migrate
      - run: python manage.py test # run tests
  build_container:
    runs-on: ubuntu-latest # operating system your code will run on
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: "registry.ifflaender-family.de"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./app
          push: true
          tags: registry.ifflaender-family.de/lukas/bookkeeping:latest